spring.application.name=cdc-materialized-view

spring.datasource.url=jdbc:mysql://localhost:3306/cdcdemo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.open-in-view=false
spring.sql.init.mode=always

debezium.db.hostname=localhost
debezium.db.port=3306
debezium.db.user=debezium
debezium.db.password=dbzpass
debezium.db.name=cdcdemo
debezium.offset.dir=./debezium-data