spring.application.name=cdc-materialized-view-sync

spring.datasource.url=jdbc:mysql://localhost:3306/cdcdemo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

debezium.db.hostname=localhost
debezium.db.port=3306
debezium.db.user=debezium
debezium.db.password=dbzpass
debezium.db.name=cdcdemo
debezium.offset.dir=./debezium-data